name: Release Please

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          # release-type: simple
          # optional. customize path to release-please-config.json
          config-file: .release-please-config.json
          # optional. customize path to .release-please-manifest.json
          #manifest-file: .release-please-manifest.json
          include-component-in-tag: false