name: Release Please

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install release-please
        run: npm install -g release-please

      - name: Release
        run: release-please github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
